AllCops:
  Exclude:
    - "memo/*"
  DisplayCopNames: true
  DisabledByDefault: true
  TargetRubyVersion: '2.6.6'

Bundler/OrderedGems:
  Enabled: true
Style/HashSyntax:
  Enabled: true
Layout/EmptyLines:
  Enabled: true
Layout/TrailingEmptyLines:
  Enabled: true
Layout/TrailingWhitespace:
  Enabled: true