version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout

      - run:
          name: bundle
          command: bundle install
      - run:
          name: rubocop
          command: bundle exec rubocop
