file = ARGV[0]
if file.nil? || file.empty?
  puts "Usage:\n ruby unsteganor.rb steg.png"
  puts "- the file must be generated by steganor.rb"
  exit!
end

steg_file = File.read(file).force_encoding("BINARY")
separator = steg_file[/(\*-.*\*)/]
output    = separator[/\[(.*?)\]/, 1]
_, secret = steg_file.split(separator)
File.open("#{output}_retrieved", "wb") { |file| file.print(secret) }
puts "[+] Generated output: #{output}_retrieved"
